import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import "./globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeicons/primeicons.css";
import localFont from "next/font/local";
import StoreProvider from "./StoreProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--inter",
});

const square = localFont({
  src: [
    {
      path: "./fonts/SQR721B.woff",
      weight: "700",
    },
    {
      path: "./fonts/Square721N.otf",
      weight: "400",
    },
  ],
  display: "swap",
  variable: "--square",
});

export const metadata: Metadata = {
  title: "Food Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-inter ${inter.variable} ${square.variable}`}
      >
        <StoreProvider>
          <PrimeReactProvider>{children}</PrimeReactProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
